### ISSUE TITLE
希望能有交流群

### ISSUE THREAD

**Issue by haxifang-aircos** [pudongping/larablog#3]
学习Larvel6.x看见了，感觉应该不错

**Comment by pudongping** [comment]
> 学习Larvel6.x看见了，感觉应该不错

谢谢您的评价！交流群暂时还没有，如果您希望一起交流下的话呢，可以添加我的微信，ying5198023 一起探讨。

**Comment by justbooting** [comment]
嗯~不知道作者还维护吗？我在网站上注册账户出了问题，注册信息填完后就直接跳到只有一张验证码图片的页面去了

**Comment by pudongping** [comment]
> 嗯~不知道作者还维护吗？我在网站上注册账户出了问题，注册信息填完后就直接跳到只有一张验证码图片的页面去了

还在维护着，您可以加我的微信 ying5198023 （并注明来意）。请提供您的截图，方便我排查问题，谢谢。
